export const logos = {
    angular: require( "../assets/logos/angular.png" ),
    angular2: require( "../assets/logos/angular2.png" ),
    aurelia: require( "../assets/logos/aurelia.png" ),
    backbone: require( "../assets/logos/backbone.png" ),
    bower: require( "../assets/logos/bower.png" ),
    browserify: require( "../assets/logos/browserify.png" ),
    chai: require( "../assets/logos/chai.png" ),
    clojurescript: require( "../assets/logos/clojurescript.jpg" ),
    elm: require( "../assets/logos/elm.png" ),
    ember: require( "../assets/logos/ember.png" ),
    express: require( "../assets/logos/express.png" ),
    flux: require( "../assets/logos/flux.png" ),
    grunt: require( "../assets/logos/grunt.png" ),
    gulp: require( "../assets/logos/gulp.png" ),
    hapi: require( "../assets/logos/hapi.png" ),
    immutable: require( "../assets/logos/immutable.png" ),
    jasmine: require( "../assets/logos/jasmine.png" ),
    jquery: require( "../assets/logos/jquery.gif" ),
    js: require( "../assets/logos/js.png" ),
    karma: require( "../assets/logos/karma.png" ),
    koa: require( "../assets/logos/koa.jpg" ),
    knockout: require( "../assets/logos/knockout.png" ),
    lodash: require( "../assets/logos/lodash.png" ),
    mobx: require( "../assets/logos/mobx.png" ),
    mocha: require( "../assets/logos/mocha.png" ),
    node: require( "../assets/logos/node.png" ),
    npm: require( "../assets/logos/npm.png" ),
    polymer: require( "../assets/logos/polymer.png" ),
    ramda: require( "../assets/logos/ramda.png" ),
    react: require( "../assets/logos/react.png" ),
    redux: require( "../assets/logos/redux.png" ),
    rxjs: require( "../assets/logos/rxjs.png" ),
    typescript: require( "../assets/logos/typescript.png" ),
    underscore: require( "../assets/logos/underscore.png" ),
    vue: require( "../assets/logos/vue.png" ),
    webpack: require( "../assets/logos/webpack.png" ),
    yarn: require( "../assets/logos/yarn.jpg" ),
    yeoman: require( "../assets/logos/yeoman.png" ),
};

export const images = {
    babel: require( "../assets/babel.png" ),
    babelRepl: require( "../assets/babel-repl.png" ),
    canyon: require( "../assets/canyon.png" ),
    kangaxDesktop: require( "../assets/kangax-desktop.png" ),
    kangaxMobile: require( "../assets/kangax-mobile.png" ),
    lichKing: require( "../assets/lich-king.png" ),
    map: require( "../assets/map-small.jpg" ),
};
